### ISSUE TITLE
03/24 - Team94

### ISSUE THREAD

**Issue by idgm5** [Jmagero/smashing-magazine#1]
Any comments or suggestions please add them here.

**Comment by SevlaMare** [comment]
For this project we should use a Grayscale colors only, you CSS have a few border green.

**Comment by ferbaco86** [comment]
- As a suggestion just try to use a Div element as an image container instead of the actual image, to speed up the development of the page
- Try to keep repeated CSS code to the minimum. If you need more information you can check out this article: https://speckyboy.com/good-bad-css-practices/

**Comment by idgm5** [comment]
This project is more about understanding the design logic behind a website/solution.  You have to create a wireframe that reflects the main objectives of the company (smashing magazine) wanted to accomplish in terms of visibility, attention time or even a call to action (like the book reviews in the site). 

I recommend you finish your project first before making changes and after that try to analyze your own design and compare it to the original one.  Does it have the same effects on you as the original? Is the logo the most appealing item in both sites? Do you read the top articles first before scrolling down like the original one? 

It shouldn't take you too much time at least in terms of "coding", but it should be the project that you can learn the most in the whole Html section.

You can read more about wireframes and the importance of creating them first before doing any kind of coding:

https://cacoo.com/blog/8-must-see-wireframe-examples-inspire-next-design/
https://www.invisionapp.com/inside-design/wireframe-examples/

**Comment by FrancoRosa** [comment]
Just as a good practice the order of your style files should be according to its priority.
At some point the code reviewers will tell you about this:
https://stackoverflow.com/questions/26611684/html-css-link-order
