### ISSUE TITLE
April 03

### ISSUE THREAD

**Issue by SevlaMare** [Jmagero/smashing-magazine#2]

**Comment by SevlaMare** [comment]
For this project the typography show be like the original, especially the font-size and font-weight.

**Comment by ferbaco86** [comment]
Great work so far!
On my screen there`s seems to be some overlapping between the main middle title element with the other Title.
![Captura de Pantalla 2020-04-03 a la(s) 11 15 31](https://user-images.githubusercontent.com/52765379/78370229-c2193000-759c-11ea-979e-8756374381c3.png)

**Comment by Jmagero** [comment]
resolved
